/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package chap07;

import main.MainAspectWithCache;
import org.junit.jupiter.api.Test;

class AppTest {
    @Test void appHasAGreeting() {
        MainAspectWithCache classUnderTest = new MainAspectWithCache();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
