/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package chap07;

import main.MainAspect;
import org.junit.jupiter.api.Test;

class AppTest {
    @Test void appHasAGreeting() {
        MainAspect classUnderTest = new MainAspect();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
